{% set name = "tropycal" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/55/d2/9b02e0a01a8c7384ce20b10e30bc4c51ef8a22625a8b27c117c113d6a056/tropycal-0.5.2.tar.gz
  sha256: 5b815ca4faf003929ed05aa4ea34b8c18be90a993d93894e9912a7aa7b0156e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - pyshp >=2.1
    - matplotlib-base >=2.2.2
    - networkx >=2.0.0
    - numpy >=1.14.3
    - pandas >=0.23.0
    - python >=3.6
    - requests >=2.22.0
    - scipy >=1.1.0
    - xarray >=0.10.7

test:
  imports:
    - tropycal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tropycal/tropycal
  summary: Package for retrieving and analyzing tropical cyclone data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomerburg
    - raybellwaves
